config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  post '/invitaciones' => 'invitaciones#create', :as => :invitaciones_create
  get '/csrf_meta_tags.html' => 'cache#csrf_meta_tags', :as => :csrf_meta_tags
  match '/current_session.json'=>'cache#current_session_json', :via=>'get', :as=>'current_session_json'

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_filter :add_flash_to_header
  def add_flash_to_header
    session[:flash_notice] = flash[:notice] unless flash[:notice].blank?
  end
end

app/controllers/cache_controller.rb
class CacheController < ApplicationController
  layout false
  before_filter :no_cache
  def no_cache
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate' # HTTP 1.1.
    response.headers['Pragma'] = 'no-cache' # HTTP 1.0.
    response.headers['Expires'] = '0' # Proxies.
  end
  def csrf_meta_tags
  end
  def current_session_json
    user_json = {
        :env=>Rails.env
    }
    if session[:flash_notice].present?
      user_json[:flash_notice] = session.delete(:flash_notice)
      session.delete(:flash)
    end
    render :json=>user_json
  end
end

app/controllers/invitaciones_controller.rb
class InvitacionesController < ApplicationController
  # skip_before_filter :verify_authenticity_token, :only => [:create]

  def create
    result = EmailValidator.valid?(params['email'])? subscribe_email(params['email']) : false
    mensaje = result ? "Su invitacion sera procesada a la brevedad, gracias!" : "Hubo un error en su solicitud, intente mas tarde."
    respond_to do |format|
      format.html { redirect_to root_path, :flash => { :notice => mensaje } }
    end
  end

  def subscribe_email(email)
    begin
      mailchimp = Mailchimp::API.new(ENV["MAILCHIMP-API-KEY"])
      resp = mailchimp.lists.subscribe(APP_CONFIG[:mailchimp][:list_id_for_claimed_emails],
                                       { email: email},
                                     {},
                                     'html',
                                     false)
    rescue
      resp = {}
      resp[:euid] = ''
    end
    return !resp['euid'].to_s.empty?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_esi(path)
      "<esi:include src=\"#{path}\" >>"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cache/csrf_meta_tags.html.erb
<%= csrf_meta_tags %>

app/views/cache/flash_tags.html.erb
<% if flash && flash.count > 0 %>
<% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
<% end -%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>CuantoTeCuesta.mx | Recibe dinero por darnos el precio de articulos</title>
  <!-- Fonts from Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <esi:include src="/csrf_meta_tags.html" />
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag "icons/apple-touch-icon.png", :rel=>"apple-touch-icon", :type  =>"image/png" %>
  <%= favicon_link_tag "icons/apple-touch-icon-57x57.png", :rel=>"apple-touch-icon", :sizes =>"57x57", :type=>"image/png" %>
  <%= favicon_link_tag "icons/apple-touch-icon-72x72.png", :rel=>"apple-touch-icon", :sizes =>"72x72", :type=>"image/png" %>
  <%= favicon_link_tag "icons/apple-touch-icon-114x114.png", :rel=>"apple-touch-icon", :sizes =>"114x114", :type=>"image/png" %>
  <%= favicon_link_tag "icons/apple-touch-icon-144x144.png", :rel=>"apple-touch-icon", :sizes =>"144x144", :type=>"image/png" %>
  <%= favicon_link_tag "icons/apple-touch-icon-60x60.png", :rel=>"apple-touch-icon", :sizes =>"57x57", :type=>"image/png" %>
  <%= favicon_link_tag "icons/apple-touch-icon-120x120.png", :rel=>"apple-touch-icon", :sizes =>"72x72", :type=>"image/png" %>
  <%= favicon_link_tag "icons/apple-touch-icon-76x76.png", :rel=>"apple-touch-icon", :sizes =>"114x114", :type=>"image/png" %>
  <%= favicon_link_tag "icons/apple-touch-icon-152x152.png", :rel=>"apple-touch-icon", :sizes =>"144x144", :type=>"image/png" %>

  <meta content="<%=asset_path('icons/smalltile.png')%>" name="msapplication-square70x70logo">
  <meta content="<%=asset_path('icons/mediumtile.png')%>" name="msapplication-square150x150logo">
  <meta content="<%=asset_path('icons/widetile.png')%>" name="msapplication-wide310x150logo">
  <meta content="<%=asset_path('icons/largetile.png')%>" name="msapplication-square310x310logo">


  <script type='application/ld+json'>
{
      "@context": "http://schema.org",
      "@type": "WebSite",
      "url": "http://www.cuantotecuesta.mx/",
      "author" : {
        "@context" : "http://schema.org",
        "@type" : "Organization",
        "legalName" : "CuantoTeCuesta, SA de CV",
        "description" : "Recibe dinero por darnos el precio de tu mandado!",
        "url" : "http://www.cuantotecuesta.mx",
        "logo" : "http://www.cuantotecuesta.mx/assets/c.logo.png",
        "contactPoint" : [
          { "@type" : "ContactPoint",
            "email" : "invitacion@cuantotecuesta.mx",
            "contactType" : "sales",
            "url" : "http://www.cuantotecuesta.mx"
          } ]
          }
  }
</script>
</head>
<body>
<div id="flash_container" class="notice" style="display:none;"></div>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-64517783-1', 'auto');
    ga('send', 'pageview');

</script>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><b>CuantoTeCuesta</b></a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Ya eres miembro?</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div id="headerwrap">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <h1>Recibe dinero por darnos el precio de tu mandado!</h1>
        <%= form_tag("#{invitaciones_create_path}", method: "post", role: "form", class: "form-inline") do %>
          <div class="form-group">
            <input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Entra tu email">
          </div>
          <button type="submit" class="btn btn-warning btn-lg">Invitame!</button>
        <% end %>
      </div><!-- /col-lg-6 -->
      <div class="col-lg-6">
        <img class="img-responsive" src="/assets/ipad-hand.png" alt="">
      </div><!-- /col-lg-6 -->

    </div><!-- /row -->
  </div><!-- /container -->
</div><!-- /headerwrap -->


<div class="container">
  <div class="row mt centered">
    <div class="col-lg-6 col-lg-offset-3">
      <h1>Haz tus compras<br/>y recibe dinero por darnos los precios</h1>
      <h3>Es un hecho de que vas a ir al mandado una vez por semana, sigue estos sencillos pasos y recibe dinero por medio de tarjetas de regalo por darnos la informacion que te pedimos.</h3>
    </div>
  </div><!-- /row -->

  <div class="row mt centered">
    <div class="col-lg-4">
      <img src="/assets/ser01.png" width="180" alt="">
      <h4>1 - Entra a nuestra pagina</h4>
      <p>Ahi encontraras los precios que necesitamos que ingreses a nuestra pagina, indicandote la tienda y el articulo, y en algunos casos te solicitaremos el ticket de compra.</p>
    </div><!--/col-lg-4 -->

    <div class="col-lg-4">
      <img src="/assets/ser02.png" width="180" alt="">
      <h4>2 - Haz tu mandado</h4>
      <p>Ve al mandado, busca el producto que te solicitamos en la tienda que te pedimos e ingresa el precio, puedes hacerlo directamente en nuestra pagina o guardar el ticket y hacerlo despues.</p>

    </div><!--/col-lg-4 -->

    <div class="col-lg-4">
      <img src="/assets/ser03.png" width="180" alt="">
      <h4>3 - Recibe Dinero!</h4>
      <p>Cada precio que te solicitamos tiene un valor en dinero para ti, y cuando llegues a cierta cantidad acumulada, te enviaremos tarjetas de regalo de los establecimientos de tu preferencia.</p>

    </div><!--/col-lg-4 -->
  </div><!-- /row -->
</div><!-- /container -->

<div class="container">
  <hr>
  <div class="row centered">
    <div class="col-lg-6 col-lg-offset-3">
      <%= form_tag("#{invitaciones_create_path}", method: "post", role: "form", class: "form-inline") do %>
        <div class="form-group">
          <input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Entra tu email">
        </div>
        <button type="submit" class="btn btn-warning btn-lg">Invitame!</button>
      <% end %>
    </div>
    <div class="col-lg-3"></div>
  </div><!-- /row -->
  <hr>
</div><!-- /container -->

<div class="container">
  <div class="row mt centered">
    <div class="col-lg-6 col-lg-offset-3">
      <h1>CuantoTeCuesta es para todos</h1>
      <h3>Eres ama de casa ? profesional independiente ? adolescente que necesita un dinerito extra ?<br/>Todos pueden ganar dinero.</h3>
    </div>
  </div><!-- /row -->
</div><! --/container -->

<div class="container">
  <hr>
  <div class="row centered">
    <div class="col-lg-6 col-lg-offset-3">
      <%= form_tag("#{invitaciones_create_path}", method: "post", role: "form", class: "form-inline") do %>
        <div class="form-group">
          <input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Entra tu email">
        </div>
        <button type="submit" class="btn btn-warning btn-lg">Invitame!</button>
      <% end %>
    </div>
    <div class="col-lg-3"></div>
  </div><!-- /row -->
  <hr>
</div><!-- /container -->

<div class="container">
  <div class="row mt centered">
    <div class="col-lg-6 col-lg-offset-3">
      <h1>Nuestro maravilloso <br/>Equipo</h1>
      <h3>Estos son algunos testimonios de nuestro equipo, que como tu, buscaron ganar dinero dandonos el precio de su mandado.</h3>
    </div>
  </div><!-- /row -->

  <div class="row mt centered">
    <div class="col-lg-4">
      <img class="img-circle" src="/assets/pic1.jpg" width="140" alt="">
      <h4>Pedro - Veracruz, Ver.</h4>
      <p>Al principio no era mucho, pero poco a poco fui acumulando y acabo de recibir mi primer tarjeta de regalo de 200 pesos.</p>
      </div><!--/col-lg-4 -->

    <div class="col-lg-4">
      <img class="img-circle" src="/assets/pic2.jpg" width="140" alt="">
      <h4>Celso - Monterrey, N.L.</h4>
      <p>Este sitio es una gran idea, y van a llegar muy lejos, gracias por mi ultima tarjeta de regalo!</p>
    </div><!--/col-lg-4 -->

    <div class="col-lg-4">
      <img class="img-circle" src="/assets/pic3.jpg" width="140" alt="">
      <h4>Angelica - Acapulco, Gro.</h4>
      <p>Antes de ir al mandado, abro la aplicacion y veo si hay algo que pueda incluir, no hay nada mejor que recibir dinero por comprar tu mandado.</p>
    </div><!--/col-lg-4 -->
  </div><!-- /row -->
</div><!-- /container -->

<div class="container">
  <hr>
  <div class="row centered">
    <div class="col-lg-6 col-lg-offset-3">
      <%= form_tag("#{invitaciones_create_path}", method: "post", role: "form", class: "form-inline") do %>
        <div class="form-group">
          <input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Entra tu email">
        </div>
        <button type="submit" class="btn btn-warning btn-lg">Invitame!</button>
      <% end %>
    </div>
    <div class="col-lg-3"></div>
  </div><!-- /row -->
</div><!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="/assets/bootstrap.min.js"></script>